from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field


class ContextEvidenceOut(BaseModel):
    """Why a signal has its value. `reviewed_related_mapping` rows are supporting context only and never create a signal."""

    model_config = ConfigDict(from_attributes=True)

    signal_type: str
    evidence_type: str  # reviewed_direct_mapping | reviewed_related_mapping | metric
    committee_code: str | None
    subcommittee_code: str | None
    source_url: str | None
    description: str
    metadata: dict | None = None


class AiSignalExplanationOut(BaseModel):
    type: str
    explanation: str


class AiContextOut(BaseModel):
    """An OpenAI-written explanation of the stored facts, validated against them. It explains; it never sets a signal or the flag. `generated_for` is
    'flagged' for a flagged trade, or 'manual' for an unflagged trade explained on request (an explanation, not a flag)."""

    headline: str
    summary: str
    signals: list[AiSignalExplanationOut]
    limitations: str
    generated_for: str
    model: str
    prompt_version: str
    generated_at: datetime


class TradeContextOut(BaseModel):
    """Deterministic context signals for one trade, from public data. Not a finding about anyone: see `notice`."""

    context_version: str
    mapping_version: str | None
    analyzed_at: datetime
    committee_relevance: bool | None  # True only when a reviewed + direct committee/industry mapping applies; None = unknown
    committee_relevance_reason: str | None
    trade_size_anomaly: bool | None
    trade_size_value: float | None  # derived from the disclosed range; never an exact transaction value
    trade_size_basis: str | None
    trade_size_percentile: float | None  # 0-100 among the same politician's earlier trades
    trade_size_sample_size: int | None
    disclosure_delay_signal: bool | None
    disclosure_delay_days: int | None
    excess_return_signal: bool | None
    security_return: float | None  # fractions: 0.10 == +10%
    spy_return: float | None
    excess_return: float | None
    excess_return_direction_adjusted: float | None
    excess_horizon_days: int | None
    signals: dict[str, bool | None]
    signal_count: int
    secondary_signal_count: int | None = None  # how many of size / delay / excess are true
    committee_temporal_status: str | None = None  # temporally_verified | current_assignment_only | unavailable
    meets_flag_rule: bool | None = None  # committee relevance plus enough secondary signals, before the temporal check
    flag_pending_temporal_verification: bool = False  # the rule is met but seat timing is not established, so the trade is not flagged
    flagged_for_contextual_review: bool
    evidence: list[ContextEvidenceOut]
    notice: str
    ai_context: AiContextOut | None = None  # optional, generated by `python -m poltracker.analyze_trade_context_llm`; null when none exists or the context has changed since


class TradeOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    source: str
    politician_id: int
    security_id: int | None
    politician_name: str
    chamber: str
    party: str | None
    state: str | None
    ticker: str | None
    asset_name: str | None
    transaction_type: str
    transaction_date: date
    disclosure_date: date | None
    amount_min: int | None
    amount_max: int | None
    source_url: str | None
    group_key: str | None = None  # same politician + security + transaction date + type; for display grouping only, rows are never merged
    group_size: int | None = None  # how many disclosed rows share that group_key (owner codes may differ; each is a separate disclosure)
    context: TradeContextOut | None = None  # null until `python -m poltracker.analyze_trade_context` has run


class TradePageOut(BaseModel):
    items: list[TradeOut]
    total: int
    limit: int
    offset: int


class PoliticianOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    chamber: str
    party: str | None
    state: str | None
    trade_count: int = 0
    latest_trade_date: date | None = None
    # Official enrichment; all null until a politician has been verified against an official roster.
    bioguide_id: str | None = None
    district: str | None = None
    official_url: str | None = None
    active: bool | None = None
    term_start_year: int | None = None
    term_end_year: int | None = None
    enriched_at: datetime | None = None
    enrichment_source: str | None = None
    enrichment_status: str | None = None  # matched | unmatched | ambiguous | conflict | review | null (never attempted)
    enrichment_method: str | None = None  # how it matched: exact_name+chamber, name_with_extra_middle+chamber, override, llm


class CommitteeOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    committee_name: str
    committee_code: str
    subcommittee_name: str | None
    subcommittee_code: str
    role: str
    chamber: str
    start_date: date | None
    end_date: date | None
    source: str
    source_url: str | None


class PoliticianDetailOut(PoliticianOut):
    committees: list[CommitteeOut] = []


class PoliticianPageOut(BaseModel):
    items: list[PoliticianOut]
    total: int
    limit: int
    offset: int


class SecurityOut(BaseModel):
    id: int
    ticker: str
    name: str | None
    price_status: str | None = None
    price_from: date | None = None
    price_to: date | None = None
    trade_count: int
    latest_trade_date: date | None
    recent_trades: list[TradeOut]
    # Official company profile (SEC EDGAR); all null until the security has been enriched or when the source does not list it.
    company_name: str | None = None
    cik: str | None = None
    sic_code: str | None = None
    industry: str | None = None  # SIC description
    sector: str | None = None  # SIC division
    exchange: str | None = None
    profile_status: str | None = None  # ok | partial | unresolved | null (never attempted)
    profile_source_url: str | None = None


class PriceBarOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    date: date
    open: float | None
    high: float | None
    low: float | None
    close: float | None
    adj_close: float | None
    volume: int | None


class PriceSeriesOut(BaseModel):
    ticker: str
    price_status: str | None
    price_from: date | None
    price_to: date | None
    bars: list[PriceBarOut]


class LegOut(BaseModel):
    status: str
    anchor_date: date | None = None
    price: float | None = None
    return_: float | None = Field(None, serialization_alias="return", validation_alias="return_")
    benchmark_return: float | None = None
    excess_return: float | None = None

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


class PerformanceOut(BaseModel):
    """Returns are fractions of adjusted close (0.10 = +10%). `direction_adjusted` flips sign for sells."""

    status: str
    detail: str | None = None
    benchmark: str | None = None
    latest_date: date | None = None
    latest_price: float | None = None
    direction: int | None = None
    transaction: LegOut | None = None
    disclosure: LegOut | None = None
    direction_adjusted: dict[str, float | None] = {}

    model_config = ConfigDict(from_attributes=True)


class TradePerformanceOut(BaseModel):
    trade: TradeOut
    performance: PerformanceOut


class SecurityPerformanceOut(BaseModel):
    ticker: str
    benchmark: str
    status_counts: dict[str, int]
    total: int
    items: list[TradePerformanceOut]


class DailyCount(BaseModel):
    date: date
    count: int


class MonthlyCount(BaseModel):
    month: str  # YYYY-MM, by disclosure date
    buys: int
    sells: int
    other: int


class TopTicker(BaseModel):
    ticker: str
    name: str | None
    trades: int
    buys: int
    sells: int


class TopPolitician(BaseModel):
    id: int
    name: str
    chamber: str
    trades: int


class OverviewTotals(BaseModel):
    trades: int
    politicians: int
    securities: int
    trades_in_window: int
    buys_in_window: int
    sells_in_window: int


class OverviewOut(BaseModel):
    window_days: int
    totals: OverviewTotals
    latest_disclosure_date: date | None
    daily: list[DailyCount]
    monthly: list[MonthlyCount]
    top_tickers: list[TopTicker]
    top_politicians: list[TopPolitician]


class StatusOut(BaseModel):
    trades_total: int
    trades_by_source: dict[str, int]
    politicians_total: int
    latest_disclosure_date: date | None
    latest_transaction_date: date | None
    last_ingested_at: datetime | None  # when the newest trade row was inserted
    last_successful_ingest_at: datetime | None  # when the last ingest run finished without error
    ingest_age_hours: float | None
    ingest_stale_after_hours: float
    ingest_stale: bool
    invalid_date_trades: int
    securities_total: int
    securities_priced: int
    securities_unavailable: int
    securities_pending: int
    price_bars: int
    latest_bar_date: date | None
    benchmark_ticker: str
    benchmark_from: date | None
    benchmark_to: date | None
    benchmark_status: str | None
