"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 18:22:59.362915
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_politicians')),
    sa.UniqueConstraint('canonical_key', name=op.f('uq_politicians_canonical_key'))
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('ticker', name=op.f('uq_securities_ticker'))
    )
    op.create_table('price_bars',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_price_bars_security_id_securities')),
    sa.PrimaryKeyConstraint('security_id', 'date', name=op.f('pk_price_bars'))
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_trade_id', sa.String(length=100), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('politician_name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=10), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('asset_name', sa.String(length=300), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('amount_min', sa.BigInteger(), nullable=True),
    sa.Column('amount_max', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], name=op.f('fk_trades_politician_id_politicians')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_trades_security_id_securities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_trades_fingerprint'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_disclosure_date', ['disclosure_date'], unique=False)
        batch_op.create_index('ix_trades_politician_id', ['politician_id'], unique=False)
        batch_op.create_index('ix_trades_source_source_trade_id', ['source', 'source_trade_id'], unique=False)
        batch_op.create_index('ix_trades_ticker', ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_ticker')
        batch_op.drop_index('ix_trades_source_source_trade_id')
        batch_op.drop_index('ix_trades_politician_id')
        batch_op.drop_index('ix_trades_disclosure_date')

    op.drop_table('trades')
    op.drop_table('price_bars')
    op.drop_table('securities')
    op.drop_table('politicians')
    # ### end Alembic commands ###
