"""add price coverage to securities

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 18:28:15.553778
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('price_to', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('price_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('price_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_column('price_checked_at')
        batch_op.drop_column('price_status')
        batch_op.drop_column('price_to')
        batch_op.drop_column('price_from')

    # ### end Alembic commands ###
