"""add ingest state

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 22:22:57.342318
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_state',
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('backfill_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_ingest_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingest_state')
    # ### end Alembic commands ###
