"""add last success to ingest state

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 23:27:31.635494
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_success_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_state', schema=None) as batch_op:
        batch_op.drop_column('last_success_at')

    # ### end Alembic commands ###
